name: Deploy Web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd web
          npm install

      - name: Build Next.js
        run: |
          cd web
          npm run build

      # Aquí iría tu paso de deploy a Vercel, Netlify, etc.
